tap "homebrew/bundle"
tap "homebrew/services"
tap "jesseduffield/lazydocker"
tap "jesseduffield/lazygit"
tap "jstkdng/programs"
tap "koekeishiya/formulae"
tap "oven-sh/bun"
brew "bat"
brew "chafa"
brew "colima", restart_service: true
brew "docker"
brew "docker-compose"
brew "docker-credential-helper"
brew "eza"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "git"
brew "git-delta"
brew "gnupg"
brew "go"
brew "jenv"
brew "jq"
brew "luarocks"
brew "mas"
brew "neovim", args: ["HEAD"]
brew "nvm"
brew "pinentry-mac"
brew "pyenv"
brew "ripgrep"
brew "rust-analyzer"
brew "rustup"
brew "silicon"
brew "stow"
brew "thefuck"
brew "wakeonlan"
brew "zoxide"
brew "jesseduffield/lazydocker/lazydocker"
brew "jesseduffield/lazygit/lazygit"
brew "koekeishiya/formulae/yabai"
brew "oven-sh/bun/bun"
cask "altserver"
cask "chatgpt"
cask "discord"
cask "font-meslo-lg-nerd-font"
cask "font-noto-color-emoji"
cask "font-roboto"
cask "font-sf-pro"
cask "jordanbaird-ice"
cask "karabiner-elements"
cask "librewolf"
cask "raycast"
cask "sf-symbols"
cask "transmission"
cask "wezterm"
cask "yabaiindicator"
cask "zoom"
mas "AdGuard for Safari", id: 1440147259
mas "Affinity Designer 2", id: 1616831348
mas "Affinity Photo 2", id: 1616822987
mas "Affinity Publisher 2", id: 1606941598
mas "Developer", id: 640199958
mas "Jump Desktop", id: 524141863
mas "Keynote", id: 409183694
mas "Messenger", id: 1480068668
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Vimkey", id: 1585682577
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
