apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-install
  namespace: flux-system
spec:
  interval: 10m
  path: ./gitops/espresso/infrastructure/longhorn/install
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
