apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: espresso-0
  namespace: longhorn-system
spec:
  disks:
    root:
      path: /var/lib/longhorn
      allowScheduling: true
      storageReserved: 75000000000
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: espresso-1
  namespace: longhorn-system
spec:
  disks:
    root:
      path: /var/lib/longhorn
      allowScheduling: true
      storageReserved: 75000000000
    data1:
      path: /data/disk1
      allowScheduling: true
    data2:
      path: /data/disk2
      allowScheduling: true
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: espresso-2
  namespace: longhorn-system
spec:
  disks:
    root:
      path: /var/lib/longhorn
      allowScheduling: true
      storageReserved: 75000000000
    data1:
      path: /data/disk1
      allowScheduling: true
    data2:
      path: /data/disk2
      allowScheduling: true
